#!/usr/bin/env bash
set -e

# install Python
apt update
wget https://www.python.org/ftp/python/3.7.10/Python-3.7.10.tgz
tar -xf Python-3.7.10.tgz
cd Python-3.7.10
./configure
make install

alias python='python3.7'

# install CommonRoad drivability checker
python3.7 -m pip install --no-cache-dir pybind11
python3.7 -m pip install --no-cache-dir wheel
python3.7 -m pip install --no-cache-dir setuptools
python3.7 -m pip install --no-cache-dir celluloid
python3.7 -m pip install --no-cache-dir commonroad-drivability-checker
python3.7 -m pip install --no-cache-dir triangle
